services:
  perplexica:
    image: itzcrazykns1337/perplexica:latest
    build:
      context: .
    ports:
      - '3020:3000'
    environment:
      - LM_STUDIO_BASE_URL=http://10.10.0.137:1234
    dns:
      - 10.10.0.1
    volumes:
      - data:/home/perplexica/data
    restart: unless-stopped

volumes:
  data:
    name: 'perplexica-data'
